package com.aerolinea.entidad;
// Generated 24-jun-2018 10:23:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paises generated by hbm2java
 */
@Entity
@Table(name="paises"
    ,catalog="aerolinea"
)
public class Paises  implements java.io.Serializable {


     private Integer idpais;
     private String pais;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
     private Set<Aeropuertos> aeropuertoses = new HashSet<Aeropuertos>(0);

    public Paises() {
    }

	
    public Paises(String pais) {
        this.pais = pais;
    }
    public Paises(String pais, Set<Usuarios> usuarioses, Set<Aeropuertos> aeropuertoses) {
       this.pais = pais;
       this.usuarioses = usuarioses;
       this.aeropuertoses = aeropuertoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpais", unique=true, nullable=false)
    public Integer getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(Integer idpais) {
        this.idpais = idpais;
    }

    
    @Column(name="pais", nullable=false, length=50)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paises")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paises")
    public Set<Aeropuertos> getAeropuertoses() {
        return this.aeropuertoses;
    }
    
    public void setAeropuertoses(Set<Aeropuertos> aeropuertoses) {
        this.aeropuertoses = aeropuertoses;
    }




}


