package com.aerolinea.entidad;
// Generated 24-jun-2018 10:23:22 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reservaciones generated by hbm2java
 */
@Entity
@Table(name="reservaciones"
    ,catalog="aerolinea"
)
public class Reservaciones  implements java.io.Serializable {


     private Integer idreservacion;
     private Usuarios usuarios;
     private Vuelos vuelos;
     private int nboletos;

    public Reservaciones() {
    }

    public Reservaciones(Usuarios usuarios, Vuelos vuelos, int nboletos) {
       this.usuarios = usuarios;
       this.vuelos = vuelos;
       this.nboletos = nboletos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idreservacion", unique=true, nullable=false)
    public Integer getIdreservacion() {
        return this.idreservacion;
    }
    
    public void setIdreservacion(Integer idreservacion) {
        this.idreservacion = idreservacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvuelo", nullable=false)
    public Vuelos getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Vuelos vuelos) {
        this.vuelos = vuelos;
    }

    
    @Column(name="nboletos", nullable=false)
    public int getNboletos() {
        return this.nboletos;
    }
    
    public void setNboletos(int nboletos) {
        this.nboletos = nboletos;
    }




}


