package com.aerolinea.entidad;
// Generated 24-jun-2018 10:23:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "aerolinea"
)
public class Usuarios implements java.io.Serializable {

    @NotEmpty(message = "Introduzca nombre de usuario.")
    private String idusuario;
    private Paises paises;
    private Roles roles;
    private String nombres;
    private String apellidos;
    @Email(message = "Introduzca mail.")
    private String email;
    private String telefono;
    private String clave;
    private Set<Reservaciones> reservacioneses = new HashSet<Reservaciones>(0);

    public Usuarios() {
    }

    public Usuarios(String idusuario, Paises paises, Roles roles, String nombres, String apellidos, String email, String clave) {
        this.idusuario = idusuario;
        this.paises = paises;
        this.roles = roles;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.clave = clave;
    }

    public Usuarios(String idusuario, Paises paises, Roles roles, String nombres, String apellidos, String email, String telefono, String clave, Set<Reservaciones> reservacioneses) {
        this.idusuario = idusuario;
        this.paises = paises;
        this.roles = roles;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.telefono = telefono;
        this.clave = clave;
        this.reservacioneses = reservacioneses;
    }

    @Id

    @Column(name = "idusuario", unique = true, nullable = false, length = 30)
    public String getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idpais", nullable = false)
    public Paises getPaises() {
        return this.paises;
    }

    public void setPaises(Paises paises) {
        this.paises = paises;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idrol", nullable = false)
    public Roles getRoles() {
        return this.roles;
    }

    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    @Column(name = "nombres", nullable = false, length = 45)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "apellidos", nullable = false, length = 45)
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "telefono", length = 20)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "clave", nullable = false, length = 100)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
    public Set<Reservaciones> getReservacioneses() {
        return this.reservacioneses;
    }

    public void setReservacioneses(Set<Reservaciones> reservacioneses) {
        this.reservacioneses = reservacioneses;
    }

}
