package com.aerolinea.entidad;
// Generated 24-jun-2018 10:23:22 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Vuelos generated by hbm2java
 */
@Entity
@Table(name = "vuelos", catalog = "aerolinea"
)
public class Vuelos implements java.io.Serializable {

    private Integer idvuelo;
    private Aeropuertos aeropuertosByIdorigen;
    private Aeropuertos aeropuertosByIddestino;
    private Aviones aviones;
    @NotNull(message = "Digite una fecha correcta dd/mm/yyyy")
    private Date fecha;
    @NotEmpty
    private String estado;
    @NotNull(message = "Digite precio")
    @DecimalMax(value = "999.99", message = "El valor ${validatedValue} decimal no puede ser mayor a 999.99")
    @DecimalMin(value = "1.00", message = "El valor ${validatedValue} decimal no puede ser menor a 1.00")
    @Digits(integer = 3, fraction = 2, message = "El formato del precio es 3 enteros 2 decimales como maximo")

    private BigDecimal precio;
    private Set<Reservaciones> reservacioneses = new HashSet<Reservaciones>(0);

    public Vuelos() {
    }

    public Vuelos(Aeropuertos aeropuertosByIdorigen, Aeropuertos aeropuertosByIddestino, Aviones aviones, Date fecha) {
        this.aeropuertosByIdorigen = aeropuertosByIdorigen;
        this.aeropuertosByIddestino = aeropuertosByIddestino;
        this.aviones = aviones;
        this.fecha = fecha;
    }

    public Vuelos(Aeropuertos aeropuertosByIdorigen, Aeropuertos aeropuertosByIddestino, Aviones aviones, Date fecha, String estado, BigDecimal precio, Set<Reservaciones> reservacioneses) {
        this.aeropuertosByIdorigen = aeropuertosByIdorigen;
        this.aeropuertosByIddestino = aeropuertosByIddestino;
        this.aviones = aviones;
        this.fecha = fecha;
        this.estado = estado;
        this.precio = precio;
        this.reservacioneses = reservacioneses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idvuelo", unique = true, nullable = false)
    public Integer getIdvuelo() {
        return this.idvuelo;
    }

    public void setIdvuelo(Integer idvuelo) {
        this.idvuelo = idvuelo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idorigen", nullable = false)
    public Aeropuertos getAeropuertosByIdorigen() {
        return this.aeropuertosByIdorigen;
    }

    public void setAeropuertosByIdorigen(Aeropuertos aeropuertosByIdorigen) {
        this.aeropuertosByIdorigen = aeropuertosByIdorigen;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "iddestino", nullable = false)
    public Aeropuertos getAeropuertosByIddestino() {
        return this.aeropuertosByIddestino;
    }

    public void setAeropuertosByIddestino(Aeropuertos aeropuertosByIddestino) {
        this.aeropuertosByIddestino = aeropuertosByIddestino;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idavion", nullable = false)
    public Aviones getAviones() {
        return this.aviones;
    }

    public void setAviones(Aviones aviones) {
        this.aviones = aviones;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 19)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "estado", length = 13)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "precio", precision = 8)
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "vuelos")
    public Set<Reservaciones> getReservacioneses() {
        return this.reservacioneses;
    }

    public void setReservacioneses(Set<Reservaciones> reservacioneses) {
        this.reservacioneses = reservacioneses;
    }

}
